# https://bun.sh/docs/runtime/bunfig

# package manager configuration here
[install]
optional = true
dev = true
peer = true
production = false # Ignore dev dependencies. Use --production in the CLI to override.
globalDir = "$HOME/.cache/.bun/install/global"
globalBinDir = "$HOME/.cache}/.bun/bin"

[install.cache]
dir = "$HOME/.cache/.bun/install/cache"
